import Head from "next/head";
import { useRouter } from "next/router";
import { FormEvent } from "react";
import { v4 } from "uuid";

export default function Home() {
  const router = useRouter();

  const handleCreateSession = (e: FormEvent) => {
    e.preventDefault();
    router.push(`/session/${v4()}`);
  };

  return (
    <div>
      <Head>
        <title>Session</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex flex-col justify-center items-center gap-16">
        <h1 className="text-7xl text-primary">SESSION</h1>
        <button onClick={handleCreateSession} className="btn btn-primary">
          Create a session
        </button>
      </main>
    </div>
  );
}
